version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root

    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
  redis:
    image: redis
    ports:
      - 6379:6379
